name: STDecNet
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - pip=25.3=pyh0d26453_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.14.2=h90eec9f_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.4.0
      - anyio==4.12.1
      - certifi==2026.1.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - easydict==1.13
      - einops==0.8.2
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - fvcore==0.1.5.post20221221
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.5
      - idna==3.11
      - imageio==2.37.2
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - loguru==0.7.3
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.3.5
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - opencv-python==4.13.0.90
      - openpyxl==3.1.5
      - osa==0.2.3
      - packaging==26.0
      - pandas==3.0.0
      - pillow==12.0.0
      - portalocker==3.2.0
      - psutil==7.2.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - setuptools==70.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.3.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2026.1.28
      - timm==1.0.24
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - tqdm==4.67.2
      - triton==3.5.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - yacs==0.1.8
prefix: /home/greekinroma/miniconda3/envs/STDecNet
